### ISSUE TITLE
[请求] 添加（符合 GH 标准的）许可证文件

### ISSUE THREAD

**Issue by MarcoRavich** [taellinglin/lingyue#1]
[Google-CHI]

大家好，首先感谢你们的出色工作！

由于我们已经在我们的 [HyMPS 项目](https://forart.it/HyMPS) 中将其“公开”了（在 [AUDIO 部分](https://github.com/forart/HyMPS#- ) \ [DAWs 页面](https://github.com/forart/HyMPS/blob/main/Audio/DAWs.md#-- ) \ [通用的](https://github.com/forart/HyMPS/blob/main/Audio/DAWs.md#generic-) 下），你们能否为其添加符合 GH 的许可文件？

如您所知，明确许可条款对于让任何人更好/更快地了解如何在其他开放项目中重用/调整/修改源代码（而不仅仅是）以及反之亦然非常重要。

虽然这听起来像是一个小问题，但许可证文件的遗漏显然也会导致相关徽章的生成不一致：

![](https://badgen.net/github/license/taellinglin/lingyue)
(徽章生成器网址：https://badgen.net/github/license/taellinglin/lingyue)

您可以通过 GH 的许可证向导工具轻松设置标准化徽章。

最后但并非最不重要的是，请让我们知道我们如何改进（您认为）我们的分类和资源链接，以促进所列项目的开发人员之间的协作（从而促进发展）。

希望对您有所帮助/启发！

Hi there, 1st of all thanks for your interesting work !

Since we've "doxed" it in our [HyMPS project](https://forart.it/HyMPS) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [DAWs page](https://github.com/forart/HyMPS/blob/main/Audio/DAWs.md#--) \ [Generic subsection](https://github.com/forart/HyMPS/blob/main/Audio/DAWs.md#generic-)), can you please add a "GH-compliant" license file ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify your "sources" (and not only) in other open projects and vice-versa.

Although it may _sounds_ like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/taellinglin/lingyue)
(badge-generator URL: https://badgen.net/github/license/taellinglin/lingyue)

Anyway you can easily choose a "correct" one through the GH's license wizard tool.

Anyway you can easily set a standard one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by MarcoRavich** [comment]
Bump (request updated).

**Comment by taellinglin** [comment]
Sure, I will add that! Have you seen my subsynth vst as well?

**Comment by MarcoRavich** [comment]
> Have you seen my subsynth vst as well?
> 
Very interesting, we'll certainly add it to the collection.

But under which section/subsection do you suggest to list it? 
[Synths](https://github.com/forart/HyMPS/blob/main/Audio/Synths.md#--) maybe ?

**Comment by taellinglin** [comment]
Yes! It's a subtractive synth with some ~30ish parameters...I am still
working on it a bit and may update it at some point...it's written in Rust.

**Comment by MarcoRavich** [comment]
Bump 2 (request has been google-translated): any news ?

note: SubSynth added !

**Comment by taellinglin** [comment]
我刚刚添加了许可证！

**Comment by MarcoRavich** [comment]
Great, thanks !

Badge is going to update...

**Comment by MarcoRavich** [comment]
Updated !
